CONTROLLER_HEART_BEAT_EXPIRATION = 90
WORKER_HEART_BEAT_INTERVAL = 30
WORKER_API_TIMEOUT = 2000

LOGDIR = "/home/xupeng/VLP_web/server_utils/runtime_log"
CONVERSATION_SAVE_DIR = '/nvme/data1/VLP_web_data/conversation_data'


rules_markdown = """ ### Rules
- Vote for large multi-modality models on VQA.
- Load an image and ask a question or click following examples. 
- Only one question is supported per round.
- Two models are anonymous before your vote.
- Click “Clear history” to start a new round.
- [[GitHub]](https://github.com/OpenGVLab/Multi-modality-Arena)
"""


notice_markdown = """ ### Terms of use
To use this service, users must agree to the following conditions: This service is an experimental research tool for non-commercial purposes only. It has limited safeguards and may generate inappropriate content. It cannot be used for anything illegal, harmful, violent, racist or sexual. The service collects data on user conversations and may distribute this data under a Creative Commons Attribution (CC-BY) license.
"""


license_markdown = """ ### License
The service is a research preview intended for non-commercial use only, subject to the model [License](https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md) of LLaMA, [Terms of Use](https://openai.com/policies/terms-of-use) of the data generated by OpenAI, and [Privacy Practices](https://chrome.google.com/webstore/detail/sharegpt-share-your-chatg/daiacboceoaocpibfodeljbdfacokfjb) of ShareGPT. Please contact us if you find any potential violation.
"""